# Generated by Django 4.0.4 on 2022-04-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='date_begin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date_paid',
            field=models.DateField(),
        ),
    ]
