# Generated by Django 4.0.4 on 2022-04-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_alter_payment_receipt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paid_from',
            field=models.CharField(choices=[('January', 'January'), (' February', ' February'), (' March', ' March'), (' April', ' April'), (' May', ' May'), (' June', ' June'), (' July', ' July'), (' August', ' August'), (' September', ' September'), (' October', ' October'), (' November', ' November'), (' December', ' December')], default='January', max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='paid_to',
            field=models.CharField(choices=[('January', 'January'), (' February', ' February'), (' March', ' March'), (' April', ' April'), (' May', ' May'), (' June', ' June'), (' July', ' July'), (' August', ' August'), (' September', ' September'), (' October', ' October'), (' November', ' November'), (' December', ' December')], default='January', max_length=50),
        ),
    ]
